* Day 11: Space Police

On the way to Jupiter, you're pulled over by the Space Police.

"Attention, unmarked spacecraft! You are in violation of Space Law! All spacecraft must have a
clearly visible registration identifier! You have 24 hours to comply or be sent to Space Jail!"

Not wanting to be sent to Space Jail, you radio back to the Elves on Earth for help. Although it
takes almost three hours for their reply signal to reach you, they send instructions for how to
power up the emergency hull painting robot and even provide a small Intcode program (your puzzle
input) that will cause it to paint your ship appropriately.

There's just one problem: you don't have an emergency hull painting robot.

You'll need to build a new emergency hull painting robot. The robot needs to be able to move around
on the grid of square panels on the side of your ship, detect the color of its current panel, and
paint its current panel black or white. (All of the panels are currently black.)

The Intcode program will serve as the brain of the robot. The program uses input instructions to
access the robot's camera: provide 0 if the robot is over a black panel or 1 if the robot is over a
white panel. Then, the program will output two values:
- First, it will output a value indicating the color to paint the panel the robot is over: 0 means
  to paint the panel black, and 1 means to paint the panel white.
- Second, it will output a value indicating the direction the robot should turn: 0 means it should
  turn left 90 degrees, and 1 means it should turn right 90 degrees.

After the robot turns, it should always move forward exactly one panel. The robot starts facing up.

The robot will continue running for a while like this and halt when it is finished drawing. Do not
restart the Intcode computer inside the robot during this process.

For example, suppose the robot is about to start running. Drawing black panels as ., white panels as
#, and the robot pointing the direction it is facing (< ^ > v), the initial state and region near
the robot looks like this:

.....
.....
..^..
.....
.....

The panel under the robot (not visible here because a ^ is shown instead) is also black, and so any
input instructions at this point should be provided 0. Suppose the robot eventually outputs 1 (paint
white) and then 0 (turn left). After taking these actions and moving forward one panel, the region
now looks like this:

.....
.....
.<#..
.....
.....

Input instructions should still be provided 0. Next, the robot might output 0 (paint black) and then
0 (turn left):

.....
.....
..#..
.v...
.....

After more outputs (1,0, 1,0):

.....
.....
..^..
.##..
.....

The robot is now back where it started, but because it is now on a white panel, input instructions
should be provided 1. After several more outputs (0,1, 1,0, 1,0), the area looks like this:

.....
..<#.
...#.
.##..
.....

Before you deploy the robot, you should probably have an estimate of the area it will cover:
specifically, you need to know the number of panels it paints at least once, regardless of color. In
the example above, the robot painted 6 panels at least once. (It painted its starting panel twice,
but that panel is still only counted once; it also never painted the panel it ended on.)

Build a new emergency hull painting robot and run the Intcode program on it. How many panels does it
paint at least once?

file:day_11_input.csv

Hackety hack:
file:hull_painter.rb
file:spec/hull_painting_robot_spec.rb

: time rbenv exec ruby hull_painter.rb day_11_input.csv
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
....................................11..........................................
...................................101.........11...............................
...................................0011......1111.............00................
.................................101101.11...010111....1111..01110111...........
................................110110..00...110101....10000100001001...........
.............................11.110110..110.010111......1111100000001...........
.............................101010001.010101110001........1101001011...........
..............................111011000001011011011..11.....10001001001.........
..............................00010100110001001011..1001.......101101101........
.............................00000010011011000010100101111.....011010101111.....
.............................01010110111000001111101111101....10101111011101....
..............................111000010000011100011000111.....11.111111110101...
..............................10010111001111111100011110010111011101001100001...
..............................101010111101000111010.101010100101010010110110....
..............................11111111101010100010001101010111.11111001011101...
............................1100101001010010010110110.1110011001..00011000.11...
............................1000000000001010101011000101110000100010000111......
............................1110111011100110111100001111010100110010110101......
............................001011011011101110010111111010000000111100010.......
............................100010101011010111000010100010100110110000011.......
.............................11100110110001011010100111100001011101010..........
.............................010011000110101000011111001001100110110111.........
............................1000010100101001111110110001110100100011000.........
............................10011010..100011100011100101010101111000100.........
.............................11..110....1111001101101101010000011110101.........
..................................11...10010000101100111111100101111001.........
......................................101110010110111011011000111011111.........
...................................11100000011011100000001010111010011..........
...................................11100111000001000011000010101110011..........
....................................01011010101110100110000100011110............
............................110110..10111100000110001110010010000011............
...........................10011110010001011011110010001110110000001............
...........................111011101110010111110011001100010.011000.............
..............................1101001001011001101100011010111101001.............
..............................1100001011110110101110110011001111110001..........
.............................10010011100010101011100100..01010111001011.........
.............................101011100100111010001001011.11110100000011111......
..............................0111010101000011.1110001101100.10001000100001.....
..............................010101000011001111101111001001011111100..1111.....
..............................100010010000110111100000110110011000001...........
...............................100001011000011.110111100110110.110.11...........
...............................011101010010110....1110101011110001..............
..............................1000110101010110....010110001100001...............
..............................01001111011001101..10000001111001.................
..............................10101010111111..1100.000101111100.................
................................11111010101...1111.0101.00001001................
..................................101001111...101..101...0010010................
...................................111000111.......11....101.1001...............
..................................1000100101...................11...............
.................................101110101011...................................
.................................11..11110011...................................
......................................100100....................................
......................................11........................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
painted 1732 panels

real    0m0,760s
user    0m0,500s
sys     0m0,256s

1732 was correct, but

* Part Two

You're not sure what it's trying to paint, but it's definitely not a registration identifier. The
Space Police are getting impatient.

Checking your external ship cameras again, you notice a white panel marked "emergency hull painting
robot starting panel". The rest of the panels are still black, but it looks like the robot was
expecting to start on a white panel, not a black one.

Based on the Space Law Space Brochure that the Space Police attached to one of your windows, a valid
registration identifier is always eight capital letters. After starting the robot on a single white
panel instead, what registration identifier does it paint on your hull?

After tweaking the output somewhat:
: time rbenv exec ruby hull_painter.rb day_11_input.csv
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ █░░░░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  ██░░░░░░████░░░░░░░░░░░░░  ░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ ██ █░██░░░ █ ███░░░░████░░ ███ ███░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██ ██ ░░  ░░░██ █ █░░░░█    █    █  █░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░██ ██ ░░██ ░ █ ███░░░░░░█████       █░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ █ █   █░ █ █ ███   █░░░░░░░░██ █  █ ██░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███ ██     █ ██ ██ ██░░██░░░░░█   █  █  █░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   █ █  ██   █  █ ██░░█  █░░░░░░░█ ██ ██ █░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░      █  ██ ██    █ █  █ ████░░░░░ ██ █ █ ████░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ █ █ ██ ███     █████ █████ █░░░░█ █ ████ ███ █░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███    █     ███   ██   ███░░░░░██░████████ █ █░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█  █ ███  ████████   ████  █ ███ ███ █  ██    █░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ █ █ ████ █   ███ █ ░█ █ █ █  █ █ █  █ ██ ██ ░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█████████ █ █ █   █   ██ █ █ ███░█████  █ ███ █░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░██  █ █  █ █  █  █ ██ ██ ░███  ██  █░░   ██   ░██░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░█           █ █ █ █ ██   █ ███    █   █    ███░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░███ ███ ███  ██ ████    ████ █ █  ██  █ ██ █ █░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░  █ ██ ██ ███ ███  █ ██████ █       ████   █ ░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░█   █ █ █ ██ █ ███    █ █   █ █  ██ ██     ██░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███  ██ ██   █ ██ █ █  ████    █ ███ █ █ ░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ █  ██   ██ █ █    █████  █  ██  ██ ██ ███░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░█    █ █  █ █  ██████ ██   ███ █  █   ██   ░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░█  ██ █ ░░█   ███   ███  █ █ █ █ ████   █  ░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░██ ░░░░████  ██ ██ ██ █ █     ████ █ █░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░█  █    █ ██  ███████  █ ████  █░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ ███  █ ██ ███ ██ ██   ███ █████░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███      ██ ███       █ █ ███ █  ██░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███  ███     █    ██    █ █ ███  ██░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ █ ██ █ █ ███ █  ██    █   ████ ░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░██ ██ ░░█ ████     ██   ███  █  █     ██░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░█  ████  █   █ ██ ████  █   ███ ██      █░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░███ ███ ███  █ █████  ██  ██   █ ░ ██   ░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██ █  █  █ ██  ██ ██   ██ █ ████ █  █░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██    █ ████ ██ █ ███ ██  ██  ██████   █░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█  █  ███   █ █ █ ███  █  ░░ █ █ ███  █ ██░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ █ ███  █  ███ █   █  █ ██░████ █      █████░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ███ █ █ █    ██░███   ██ ██  ░█   █   █    █░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ █ █ █    ██  █████ ████  █  █ ██████  ░░████░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█   █  █    ██ ████     ██ ██  ██     █░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█    █ ██    ██░██ ████  ██ ██ ░██ ░██░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ███ █ █  █ ██ ░░░░███ █ █ ████   █░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█   ██ █ █ █ ██ ░░░░ █ ██   ██    █░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ █  ████ ██  ██ █░░█      ████  █░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ █ █ █ ██████░░██  ░   █ █████  ░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█████ █ █ █░░░████░ █ █░    █  █░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ █  ████░░░█ █░░█ █░░░  █  █ ░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███   ███░░░░░░░██░░░░█ █░█  █░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█   █  █ █░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ ███ █ █ ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░████  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█  █  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
painted 1732 panels
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░  ██  ███   ██  █    ████ █  █ █  █   ██  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░█  █ █  █ █  █ █    █    █  █ █  █    █   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░█  █ ███  █    █    ███  █  █ ████    █   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░ ████ █  █ █    █    █    █  █ █  █    █  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░ █  █ █  █ █  █ █    █    █  █ █  █ █  █ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░█  █ ███   ██  ████ █     ██  █  █  ██  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
painted 249 panels

real    0m0,825s
user    0m0,612s
sys     0m0,204s

