* Day 10: Monitoring Station

You fly into the asteroid belt and reach the Ceres monitoring
station. The Elves here have an emergency: they're having trouble
tracking all of the asteroids and can't be sure they're safe.

The Elves would like to build a new monitoring station in a nearby
area of space; they hand you a map of all of the asteroids in that
region (your puzzle input).

The map indicates whether each position is empty (.) or contains an
asteroid (#). The asteroids are much smaller than they appear on the
map, and every asteroid is exactly in the center of its marked
position. The asteroids can be described with X,Y coordinates where X
is the distance from the left edge and Y is the distance from the top
edge (so the top-left corner is 0,0 and the position immediately to
its right is 1,0).

Your job is to figure out which asteroid would be the best place to
build a new monitoring station. A monitoring station can detect any
asteroid to which it has direct line of sight - that is, there cannot
be another asteroid exactly between them. This line of sight can be at
any angle, not just lines aligned to the grid or diagonally. The best
location is the asteroid that can detect the largest number of other
asteroids.

For example, consider the following map:

.#..#
.....
#####
....#
...+#

The best location for a new monitoring station on this map is the
highlighted asteroid at 3,4 because it can detect 8 asteroids, more
than any other location. (The only asteroid it cannot detect is the
one at 1,0; its view of this asteroid is blocked by the asteroid at
2,2.) All other asteroids are worse locations; they can detect 7 or
fewer other asteroids. Here is the number of other asteroids a
monitoring station on each asteroid could detect:

.7..7
.....
67775
....7
...87

Here is an asteroid (#) and some examples of the ways its line of
sight might be blocked. If there were another asteroid at the location
of a capital letter, the locations marked with the corresponding
lowercase letter would be blocked and could not be detected:

#.........
...A......
...B..a...
.EDCG....a
..F.c.b...
.....c....
..efd.c.gb
.......c..
....f...c.
...e..d..c

Here are some larger examples:
- Best is 5,8 with 33 other asteroids detected:

    ......#.#.
    #..#.#....
    ..#######.
    .#.#.###..
    .#..#.....
    ..#....#.#
    #..#....#.
    .##.#..###
    ##...#..#.
    .#....####

- Best is 1,2 with 35 other asteroids detected:

    #.#...#.#.
    .###....#.
    .#....#...
    ##.#.#.#.#
    ....#.#.#.
    .##..###.#
    ..#...##..
    ..##....##
    ......#...
    .####.###.

- Best is 6,3 with 41 other asteroids detected:

    .#..#..###
    ####.###.#
    ....###.#.
    ..###.##.#
    ##.##.#.#.
    ....###..#
    ..#.#..#.#
    #..#.#.###
    .##...##.#
    .....#.#..

- Best is 11,13 with 210 other asteroids detected:

    .#..##.###...#######
    ##.############..##.
    .#.######.########.#
    .###.#######.####.#.
    #####.##.#.##.###.##
    ..#####..#.#########
    ####################
    #.####....###.#.#.##
    ##.#################
    #####.##.###..####..
    ..######..##.#######
    ####.##.####...##..#
    .#####..#.######.###
    ##...#.##########...
    #.##########.#######
    .####.#.###.###.#.##
    ....##.##.###..#####
    .#.#.###########.###
    #.#.#.#####.####.###
    ###.##.####.##.#..##

Find the best location for a new monitoring station. How many other
asteroids can be detected from that location?

The format looks like XPM2, although without the following headers:
: ! XPM2
: 39 39 2 1
: . c #000000
: # c #FFFFFF

file:day_10_input.xpm

Rename the previous days' notes:
: seq 1 9 | xargs -L1 -I% git mv 2019/day_%.org 2019/day_0%.org

file:monitoring_station.rb
file:spec/asteroid_map_spec.rb

: rbenv exec ruby monitoring_station.rb day_10_input.xpm 
,,,,,,,,,,,,,275,,,280,,283,,,,,,,281,276,,,,,,,,,280,,,292,
,274,,,,270,274,,,,,272,,,,,,,,,273,274,,263,,,,,,,283,,,,,,,284,,
,,287,,272,,273,,,,275,,,,276,,,,281,265,,274,,,,280,,,,,,,,,,,,,,
,,,,,278,278,,,,,,,,,,,,,,,,,,274,,,,,,281,272,,,283,,278,,286,
,,,,,,280,281,,,,276,,280,266,,,,,,,280,,,285,,,,,,,,276,,,,,,,
,,,,,,278,,,,,,288,,,,,280,,281,,,281,,,276,293,,,,,279,,,,,,,,
,,,,,,,,,,,,,,,,,,,280,277,,282,,,278,,,,,,275,,,,,,286,,
277,,,,,,285,,278,271,,,,,,282,,,,262,273,,,,,276,269,282,277,265,,,,,275,,283,,,
,,284,,270,,,,,,,,,,,275,,,272,274,,,,,,,,275,,275,,,,277,,,,,287,
,,,281,,286,,,290,,,,295,,,,,,,266,,,,,,,,,,,290,269,283,,283,,,,,
280,276,,,280,273,,,,281,,267,,,,,,,,262,273,,,,,273,,272,,,276,,,,271,270,,,,
,,,,,,,,,,272,,288,,,,,286,,271,,273,,,,,,,273,,,,,,279,,,,,
,,,,261,,,,,,,,,,276,,,283,,,275,281,,,270,,284,290,,,,,,,,,280,,,
,,,,,,,,275,,,,,,,282,279,277,,,,,,,,,,,,,,,283,,274,,,,,
,,,282,278,,279,,,,282,,278,,280,,,,,,,276,,,,,,,,,287,,,,,,,,,
,,,,,,285,279,,277,,,,,,266,,285,,,,,,285,,,285,,,,,,281,,286,,,,,
,,276,,,,,282,,289,278,265,,,269,,,,278,276,,284,,,283,278,,,,,,,,,,,,,268,
,,,273,273,,,284,,,,282,,276,278,,273,,276,,,,,286,,270,,,,,,276,,,,281,,,291,
,,,,,,279,,,,,,,,,,,,,270,,285,284,,,286,,,281,,,,,287,276,,,,,
,274,,279,,,,,,,,273,,,275,,,,276,266,281,,,,,,,,,,,,279,,282,,281,275,,
,,,,,,,,289,278,,,,,,,,,284,,279,,,,280,,285,,,,,,,288,273,,,,,
,271,,288,,,,,,,,,285,,,,,,,275,,,,,,,,,,,290,,,,,279,,,,
,,,,,,,,,,,,,,,280,,,,278,,,,,,,,,283,266,,,280,,271,,,,,
,281,,,,,,,287,,,,,278,,,,,,,,276,,,277,,,,,,,281,,,,,,,,
,,,,,284,,,,281,,281,,,,285,,,,277,,,276,276,271,,,,,,,280,,286,274,,,,,
,274,,,,278,,,276,285,,,,,,,,,,,,,,,,,285,275,,275,,,,,,,,,,
,,284,276,276,,,,281,,,,,,,,282,,269,276,,279,,,,,288,,,,,277,,,,,283,,281,
,,,275,,,282,,,,,,,,275,287,281,,,,,,,,,,,,,,283,282,,281,,,,,,
275,,,281,270,,,,,282,281,272,,,,,,,,274,267,,,,,,,,,269,,,268,,,,277,,271,
,276,,,,,,,289,,,,274,,,,286,,281,275,,,,,,,299,,,284,,,,,,,,,,
273,,,,275,,,,,,278,,,,,,,275,,,279,273,,,,,,,,,,,,,,286,,,,
,,,277,276,269,,,,,,,,,,273,274,268,,264,272,275,,271,,,,,,278,275,266,,279,,264,,,,
268,,,,,,,287,,,,,,,275,,281,,,268,,,,,269,,,286,,,,,,281,260,,270,,,
,283,286,,,,,278,,,,,,277,,,,285,,270,283,,,278,,275,,,282,276,,,,,,,,279,,
,,271,,,,,,,,,279,,,,,,,,276,275,,282,283,,,,,277,,,,,,,279,,,,
281,276,,,,,,,,,,,,,286,,,,,272,,270,,,,,,277,,,,,,,,,,,,
,,,,,,,,278,288,280,,,,,,,,,,,,,,276,273,,,,283,,,,,,,,,273,
279,,,,,,,,,,274,,,,,,283,,,269,274,,284,,271,,270,,,264,,,,,280,,,,,
,,,,,,,,,,,,,,272,281,,282,,272,,276,,,,,,,,,,,,280,,,,,,
{:count=>299, :coordinates=>[29, 26]}

299 was correct


