* Day 9: Sensor Boost

You've just said goodbye to the rebooted rover and left Mars when you receive a faint distress
signal coming from the asteroid belt. It must be the Ceres monitoring station!

In order to lock on to the signal, you'll need to boost your sensors. The Elves send up the latest
BOOST program - Basic Operation Of System Test.

While BOOST (your puzzle input) is capable of boosting your sensors, for tenuous safety reasons, it
refuses to do so until the computer it runs on passes some checks to demonstrate it is a complete
Intcode computer.

Your existing Intcode computer is missing one key feature: it needs support for parameters in
relative mode.

Parameters in mode 2, relative mode, behave very similarly to parameters in position mode: the
parameter is interpreted as a position. Like position mode, parameters in relative mode can be read
from or written to.

The important difference is that relative mode parameters don't count from address 0. Instead, they
count from a value called the relative base. The relative base starts at 0.

The address a relative mode parameter refers to is itself plus the current relative base. When the
relative base is 0, relative mode parameters and position mode parameters with the same value refer
to the same address.

For example, given a relative base of 50, a relative mode parameter of -7 refers to memory address
50 + -7 = 43.

The relative base is modified with the relative base offset instruction:
- Opcode 9 adjusts the relative base by the value of its only parameter. The relative base increases
  (or decreases, if the value is negative) by the value of the parameter.

For example, if the relative base is 2000, then after the instruction 109,19, the relative base
would be 2019. If the next instruction were 204,-34, then the value at address 1985 would be output.

Your Intcode computer will also need a few other capabilities:
- The computer's available memory should be much larger than the initial program. Memory beyond the
  initial program starts with the value 0 and can be read or written like any other memory. (It is
  invalid to try to access memory at a negative address, though.)
- The computer should have support for large numbers. Some instructions near the beginning of the
  BOOST program will verify this capability.

Here are some example programs that use these features:
- 109,1,204,-1,1001,100,1,100,1008,100,16,101,1006,101,0,99 
  takes no input and produces a copy of itself as output.
- 1102,34915192,34915192,7,4,7,99,0 
  should output a 16-digit number.
- 104,1125899906842624,99
  should output the large number in the middle.

The BOOST program will ask for a single input; run it in test mode by providing it the value 1. It
will perform a series of checks on each opcode, output any opcodes (and the associated parameter
modes) that seem to be functioning incorrectly, and finally output a BOOST keycode.

Once your Intcode computer is fully functional, the BOOST program should report no malfunctioning
opcodes when run in test mode; it should only output a single value, the BOOST keycode. What BOOST
keycode does it produce?

file:day_9_input.csv

file:int_code.rb
file:spec/int_code_spec.rb

: bundle exec rspec
..............................................................................

Finished in 0.34546 seconds (files took 0.18867 seconds to load)
78 examples, 0 failures

: bundle exec ruby int_code.rb day_9_input.csv 
TEST>1
203
0
34463338.34463338 => 1

So, I input "1", and it output the Boost code "203"

"your answer is too low"

That's right, it actually output "203" as incorrect parameter mode & opcode.
Which means "relative mode input" is wrong, and not covered by specs either.
Have some more:
file:spec/int_code_spec.rb

After some hacking, more or less ugly:
: bundle exec rspec
...............................................................................

Finished in 0.32812 seconds (files took 0.20489 seconds to load)
79 examples, 0 failures

: bundle exec ruby int_code.rb day_9_input.csv 
TEST>1
21101
21107
21108
21102
int_code.rb:121:in `execute': Illegal instruction 0 at 1 (ArgumentError)
	from int_code.rb:87:in `run'
	from int_code.rb:280:in `run_program'
	from int_code.rb:315:in `block in <main>'
	from /Users/janne/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/csv.rb:1771:in `each'
	from /Users/janne/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/csv.rb:1148:in `block in foreach'
	from /Users/janne/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/csv.rb:1299:in `open'
	from /Users/janne/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/csv.rb:1147:in `foreach'
	from int_code.rb:315:in `<main>'

It seems I'll need to cover the same stuff in RSpec as covered by day_9_input.csv.
Issues were already anticipated by comments like 
# TODO: pmodes[2] == 1?
# TODO: pmodes[2] > 0?

Refactoring parameter handling to include relative modes:
: bundle exec rspec
...............................................................................

Finished in 0.33563 seconds (files took 0.18998 seconds to load)
79 examples, 0 failures
: bundle exec ruby int_code.rb day_9_input.csv 
TEST>1
3638931938
34463338.34463338 => 1102

3638931938 was the correct answer!


